"""architecture_drift_schema

Revision ID: 1984aeb90969
Revises: 6823e0fea4e4
Create Date: 2026-09-26 11:05:43.752634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1984aeb90969'
down_revision: Union[str, Sequence[str], None] = '6823e0fea4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('baseline_version', sa.String(length=50), nullable=False),
    sa.Column('expected_boundaries', sa.Integer(), nullable=False),
    sa.Column('validated_boundaries', sa.Integer(), nullable=False),
    sa.Column('violations_count', sa.Integer(), nullable=False),
    sa.Column('circular_count', sa.Integer(), nullable=False),
    sa.Column('unexpected_count', sa.Integer(), nullable=False),
    sa.Column('conformance_percentage', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_reports_repository_id'), 'architecture_reports', ['repository_id'], unique=False)
    op.create_index(op.f('ix_architecture_reports_snapshot_id'), 'architecture_reports', ['snapshot_id'], unique=False)
    op.create_table('architecture_drifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('expected_rule', sa.Text(), nullable=False),
    sa.Column('actual_evidence', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['architecture_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_drifts_category'), 'architecture_drifts', ['category'], unique=False)
    op.create_index(op.f('ix_architecture_drifts_report_id'), 'architecture_drifts', ['report_id'], unique=False)
    op.create_index(op.f('ix_architecture_drifts_repository_id'), 'architecture_drifts', ['repository_id'], unique=False)
    op.create_index(op.f('ix_architecture_drifts_severity'), 'architecture_drifts', ['severity'], unique=False)
    op.create_index(op.f('ix_architecture_drifts_snapshot_id'), 'architecture_drifts', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_architecture_drifts_status'), 'architecture_drifts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_architecture_drifts_status'), table_name='architecture_drifts')
    op.drop_index(op.f('ix_architecture_drifts_snapshot_id'), table_name='architecture_drifts')
    op.drop_index(op.f('ix_architecture_drifts_severity'), table_name='architecture_drifts')
    op.drop_index(op.f('ix_architecture_drifts_repository_id'), table_name='architecture_drifts')
    op.drop_index(op.f('ix_architecture_drifts_report_id'), table_name='architecture_drifts')
    op.drop_index(op.f('ix_architecture_drifts_category'), table_name='architecture_drifts')
    op.drop_table('architecture_drifts')
    op.drop_index(op.f('ix_architecture_reports_snapshot_id'), table_name='architecture_reports')
    op.drop_index(op.f('ix_architecture_reports_repository_id'), table_name='architecture_reports')
    op.drop_table('architecture_reports')
    # ### end Alembic commands ###
