"""structural_digital_twin_schema

Revision ID: 6823e0fea4e4
Revises: cac7730f01cd
Create Date: 2026-09-26 10:45:58.345991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6823e0fea4e4'
down_revision: Union[str, Sequence[str], None] = 'cac7730f01cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('process_type', sa.String(length=100), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_definitions_project_id'), 'process_definitions', ['project_id'], unique=False)
    op.create_index(op.f('ix_process_definitions_repository_id'), 'process_definitions', ['repository_id'], unique=False)
    op.create_index(op.f('ix_process_definitions_snapshot_id'), 'process_definitions', ['snapshot_id'], unique=False)
    op.create_table('structural_artifacts',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qualified_name', sa.String(length=1024), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=1024), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('analyzer_source', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_art_snap_qual', 'structural_artifacts', ['snapshot_id', 'qualified_name'], unique=False)
    op.create_index('idx_art_snap_type', 'structural_artifacts', ['snapshot_id', 'artifact_type'], unique=False)
    op.create_index(op.f('ix_structural_artifacts_artifact_type'), 'structural_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_structural_artifacts_file_id'), 'structural_artifacts', ['file_id'], unique=False)
    op.create_index(op.f('ix_structural_artifacts_language'), 'structural_artifacts', ['language'], unique=False)
    op.create_index(op.f('ix_structural_artifacts_name'), 'structural_artifacts', ['name'], unique=False)
    op.create_index(op.f('ix_structural_artifacts_qualified_name'), 'structural_artifacts', ['qualified_name'], unique=False)
    op.create_index(op.f('ix_structural_artifacts_repository_id'), 'structural_artifacts', ['repository_id'], unique=False)
    op.create_index(op.f('ix_structural_artifacts_snapshot_id'), 'structural_artifacts', ['snapshot_id'], unique=False)
    op.create_table('artifact_relationships',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=128), nullable=False),
    sa.Column('target_artifact_id', sa.String(length=128), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_method', sa.String(length=100), nullable=False),
    sa.Column('source_location', sa.String(length=1024), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['structural_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_artifact_id'], ['structural_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rel_snap_type', 'artifact_relationships', ['snapshot_id', 'relationship_type'], unique=False)
    op.create_index('idx_rel_src_tgt', 'artifact_relationships', ['source_artifact_id', 'target_artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_relationships_relationship_type'), 'artifact_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_artifact_relationships_repository_id'), 'artifact_relationships', ['repository_id'], unique=False)
    op.create_index(op.f('ix_artifact_relationships_snapshot_id'), 'artifact_relationships', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_artifact_relationships_source_artifact_id'), 'artifact_relationships', ['source_artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_relationships_target_artifact_id'), 'artifact_relationships', ['target_artifact_id'], unique=False)
    op.create_table('process_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('component_artifact_id', sa.String(length=128), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_artifact_id'], ['structural_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process_id'], ['process_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_steps_component_artifact_id'), 'process_steps', ['component_artifact_id'], unique=False)
    op.create_index(op.f('ix_process_steps_process_id'), 'process_steps', ['process_id'], unique=False)
    op.create_table('process_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('from_step_id', sa.String(length=36), nullable=False),
    sa.Column('to_step_id', sa.String(length=36), nullable=False),
    sa.Column('transition_condition', sa.String(length=255), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_step_id'], ['process_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['process_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_step_id'], ['process_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_transitions_from_step_id'), 'process_transitions', ['from_step_id'], unique=False)
    op.create_index(op.f('ix_process_transitions_process_id'), 'process_transitions', ['process_id'], unique=False)
    op.create_index(op.f('ix_process_transitions_to_step_id'), 'process_transitions', ['to_step_id'], unique=False)
    op.add_column('analysis_runs', sa.Column('repository_id', sa.String(length=36), nullable=True))
    op.add_column('analysis_runs', sa.Column('snapshot_id', sa.String(length=36), nullable=True))
    op.add_column('analysis_runs', sa.Column('analyzer_names', sa.JSON(), nullable=False))
    op.add_column('analysis_runs', sa.Column('files_scanned', sa.Integer(), nullable=False))
    op.add_column('analysis_runs', sa.Column('artifacts_created', sa.Integer(), nullable=False))
    op.add_column('analysis_runs', sa.Column('relationships_created', sa.Integer(), nullable=False))
    op.add_column('analysis_runs', sa.Column('warnings', sa.JSON(), nullable=False))
    op.add_column('analysis_runs', sa.Column('errors', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_analysis_runs_repository_id'), 'analysis_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_snapshot_id'), 'analysis_runs', ['snapshot_id'], unique=False)
    op.create_foreign_key(None, 'analysis_runs', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'analysis_runs', 'repository_snapshots', ['snapshot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'analysis_runs', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'analysis_runs', type_='foreignkey')
    op.drop_index(op.f('ix_analysis_runs_snapshot_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_repository_id'), table_name='analysis_runs')
    op.drop_column('analysis_runs', 'errors')
    op.drop_column('analysis_runs', 'warnings')
    op.drop_column('analysis_runs', 'relationships_created')
    op.drop_column('analysis_runs', 'artifacts_created')
    op.drop_column('analysis_runs', 'files_scanned')
    op.drop_column('analysis_runs', 'analyzer_names')
    op.drop_column('analysis_runs', 'snapshot_id')
    op.drop_column('analysis_runs', 'repository_id')
    op.drop_index(op.f('ix_process_transitions_to_step_id'), table_name='process_transitions')
    op.drop_index(op.f('ix_process_transitions_process_id'), table_name='process_transitions')
    op.drop_index(op.f('ix_process_transitions_from_step_id'), table_name='process_transitions')
    op.drop_table('process_transitions')
    op.drop_index(op.f('ix_process_steps_process_id'), table_name='process_steps')
    op.drop_index(op.f('ix_process_steps_component_artifact_id'), table_name='process_steps')
    op.drop_table('process_steps')
    op.drop_index(op.f('ix_artifact_relationships_target_artifact_id'), table_name='artifact_relationships')
    op.drop_index(op.f('ix_artifact_relationships_source_artifact_id'), table_name='artifact_relationships')
    op.drop_index(op.f('ix_artifact_relationships_snapshot_id'), table_name='artifact_relationships')
    op.drop_index(op.f('ix_artifact_relationships_repository_id'), table_name='artifact_relationships')
    op.drop_index(op.f('ix_artifact_relationships_relationship_type'), table_name='artifact_relationships')
    op.drop_index('idx_rel_src_tgt', table_name='artifact_relationships')
    op.drop_index('idx_rel_snap_type', table_name='artifact_relationships')
    op.drop_table('artifact_relationships')
    op.drop_index(op.f('ix_structural_artifacts_snapshot_id'), table_name='structural_artifacts')
    op.drop_index(op.f('ix_structural_artifacts_repository_id'), table_name='structural_artifacts')
    op.drop_index(op.f('ix_structural_artifacts_qualified_name'), table_name='structural_artifacts')
    op.drop_index(op.f('ix_structural_artifacts_name'), table_name='structural_artifacts')
    op.drop_index(op.f('ix_structural_artifacts_language'), table_name='structural_artifacts')
    op.drop_index(op.f('ix_structural_artifacts_file_id'), table_name='structural_artifacts')
    op.drop_index(op.f('ix_structural_artifacts_artifact_type'), table_name='structural_artifacts')
    op.drop_index('idx_art_snap_type', table_name='structural_artifacts')
    op.drop_index('idx_art_snap_qual', table_name='structural_artifacts')
    op.drop_table('structural_artifacts')
    op.drop_index(op.f('ix_process_definitions_snapshot_id'), table_name='process_definitions')
    op.drop_index(op.f('ix_process_definitions_repository_id'), table_name='process_definitions')
    op.drop_index(op.f('ix_process_definitions_project_id'), table_name='process_definitions')
    op.drop_table('process_definitions')
    # ### end Alembic commands ###
