"""discovery_brain_schema

Revision ID: cac7730f01cd
Revises: ee7d6d05e01c
Create Date: 2026-09-26 02:59:42.758263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac7730f01cd'
down_revision: Union[str, Sequence[str], None] = 'ee7d6d05e01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('supported_languages', sa.JSON(), nullable=False),
    sa.Column('supported_frameworks', sa.JSON(), nullable=False),
    sa.Column('capability_level', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyzers_name'), 'analyzers', ['name'], unique=True)
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capability_level', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_category'), 'capabilities', ['category'], unique=False)
    op.create_index(op.f('ix_capabilities_name'), 'capabilities', ['name'], unique=True)
    op.create_table('technologies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_category'), 'technologies', ['category'], unique=False)
    op.create_index(op.f('ix_technologies_name'), 'technologies', ['name'], unique=True)
    op.create_table('analysis_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan_steps', sa.JSON(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_plans_project_id'), 'analysis_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_analysis_plans_repository_id'), 'analysis_plans', ['repository_id'], unique=False)
    op.create_table('project_capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('analyzer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analyzer_id'], ['analyzers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_capabilities_analyzer_id'), 'project_capabilities', ['analyzer_id'], unique=False)
    op.create_index(op.f('ix_project_capabilities_capability_id'), 'project_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_project_capabilities_project_id'), 'project_capabilities', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_capabilities_repository_id'), 'project_capabilities', ['repository_id'], unique=False)
    op.create_table('project_technologies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('technology_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_status', sa.String(length=20), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_technologies_project_id'), 'project_technologies', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_technologies_repository_id'), 'project_technologies', ['repository_id'], unique=False)
    op.create_index(op.f('ix_project_technologies_technology_id'), 'project_technologies', ['technology_id'], unique=False)
    op.create_table('technology_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('technology_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_rule', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_evidence_evidence_type'), 'technology_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_technology_evidence_file_path'), 'technology_evidence', ['file_path'], unique=False)
    op.create_index(op.f('ix_technology_evidence_project_id'), 'technology_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_technology_evidence_repository_id'), 'technology_evidence', ['repository_id'], unique=False)
    op.create_index(op.f('ix_technology_evidence_technology_id'), 'technology_evidence', ['technology_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technology_evidence_technology_id'), table_name='technology_evidence')
    op.drop_index(op.f('ix_technology_evidence_repository_id'), table_name='technology_evidence')
    op.drop_index(op.f('ix_technology_evidence_project_id'), table_name='technology_evidence')
    op.drop_index(op.f('ix_technology_evidence_file_path'), table_name='technology_evidence')
    op.drop_index(op.f('ix_technology_evidence_evidence_type'), table_name='technology_evidence')
    op.drop_table('technology_evidence')
    op.drop_index(op.f('ix_project_technologies_technology_id'), table_name='project_technologies')
    op.drop_index(op.f('ix_project_technologies_repository_id'), table_name='project_technologies')
    op.drop_index(op.f('ix_project_technologies_project_id'), table_name='project_technologies')
    op.drop_table('project_technologies')
    op.drop_index(op.f('ix_project_capabilities_repository_id'), table_name='project_capabilities')
    op.drop_index(op.f('ix_project_capabilities_project_id'), table_name='project_capabilities')
    op.drop_index(op.f('ix_project_capabilities_capability_id'), table_name='project_capabilities')
    op.drop_index(op.f('ix_project_capabilities_analyzer_id'), table_name='project_capabilities')
    op.drop_table('project_capabilities')
    op.drop_index(op.f('ix_analysis_plans_repository_id'), table_name='analysis_plans')
    op.drop_index(op.f('ix_analysis_plans_project_id'), table_name='analysis_plans')
    op.drop_table('analysis_plans')
    op.drop_index(op.f('ix_technologies_name'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_category'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_capabilities_name'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_category'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_analyzers_name'), table_name='analyzers')
    op.drop_table('analyzers')
    # ### end Alembic commands ###
