"""initial_schema

Revision ID: ee7d6d05e01c
Revises: 
Create Date: 2026-09-26 02:54:08.551880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7d6d05e01c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dep_relation', 'dependencies', ['relation_type'], unique=False)
    op.create_index('idx_dep_source', 'dependencies', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_dep_target', 'dependencies', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_dependencies_project_id'), 'dependencies', ['project_id'], unique=False)
    op.create_index(op.f('ix_dependencies_relation_type'), 'dependencies', ['relation_type'], unique=False)
    op.create_index(op.f('ix_dependencies_source_id'), 'dependencies', ['source_id'], unique=False)
    op.create_index(op.f('ix_dependencies_source_type'), 'dependencies', ['source_type'], unique=False)
    op.create_index(op.f('ix_dependencies_target_id'), 'dependencies', ['target_id'], unique=False)
    op.create_index(op.f('ix_dependencies_target_type'), 'dependencies', ['target_type'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('env_type', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('root_cause_component_id', sa.String(length=64), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_project_id'), 'incidents', ['project_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vcs_type', sa.String(length=50), nullable=False),
    sa.Column('remote_url', sa.String(length=1024), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_project_id'), 'repositories', ['project_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_project_id'), 'scenarios', ['project_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('runtime', sa.String(length=50), nullable=True),
    sa.Column('root_directory', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_project_id'), 'services', ['project_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('head_commit_hash', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_repository_id'), 'branches', ['repository_id'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('commit_hash', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('parent_hashes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_commit_hash'), 'commits', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_commits_repository_id'), 'commits', ['repository_id'], unique=False)
    op.create_table('configurations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('config_format', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configurations_config_key'), 'configurations', ['config_key'], unique=False)
    op.create_index(op.f('ix_configurations_project_id'), 'configurations', ['project_id'], unique=False)
    op.create_index(op.f('ix_configurations_service_id'), 'configurations', ['service_id'], unique=False)
    op.create_table('database_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('schema_definition', sa.JSON(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_entities_entity_name'), 'database_entities', ['entity_name'], unique=False)
    op.create_index(op.f('ix_database_entities_project_id'), 'database_entities', ['project_id'], unique=False)
    op.create_index(op.f('ix_database_entities_service_id'), 'database_entities', ['service_id'], unique=False)
    op.create_table('repository_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('commit_hash', sa.String(length=64), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_symbols', sa.Integer(), nullable=False),
    sa.Column('snapshot_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_snapshots_commit_hash'), 'repository_snapshots', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_repository_snapshots_repository_id'), 'repository_snapshots', ['repository_id'], unique=False)
    op.create_table('runtime_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_events_event_type'), 'runtime_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_runtime_events_project_id'), 'runtime_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_runtime_events_service_id'), 'runtime_events', ['service_id'], unique=False)
    op.create_table('scenario_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('impacted_nodes', sa.JSON(), nullable=False),
    sa.Column('propagation_paths', sa.JSON(), nullable=False),
    sa.Column('risk_impact_score', sa.Float(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('simulated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_results_scenario_id'), 'scenario_results', ['scenario_id'], unique=False)
    op.create_table('changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('commit_id', sa.String(length=36), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('change_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changes_commit_id'), 'changes', ['commit_id'], unique=False)
    op.create_index(op.f('ix_changes_project_id'), 'changes', ['project_id'], unique=False)
    op.create_index(op.f('ix_changes_repository_id'), 'changes', ['repository_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['repository_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_is_test'), 'files', ['is_test'], unique=False)
    op.create_index(op.f('ix_files_language'), 'files', ['language'], unique=False)
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=False)
    op.create_index(op.f('ix_files_repository_id'), 'files', ['repository_id'], unique=False)
    op.create_index(op.f('ix_files_snapshot_id'), 'files', ['snapshot_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('change_id', sa.String(length=36), nullable=True),
    sa.Column('run_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_change_id'), 'analysis_runs', ['change_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_project_id'), 'analysis_runs', ['project_id'], unique=False)
    op.create_table('code_symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol_type', sa.String(length=50), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('is_exported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_symbols_file_id'), 'code_symbols', ['file_id'], unique=False)
    op.create_index(op.f('ix_code_symbols_name'), 'code_symbols', ['name'], unique=False)
    op.create_index(op.f('ix_code_symbols_symbol_type'), 'code_symbols', ['symbol_type'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_analysis_run_id'), 'agent_runs', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_table('api_endpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('symbol_id', sa.String(length=36), nullable=True),
    sa.Column('route_path', sa.String(length=512), nullable=False),
    sa.Column('http_method', sa.String(length=20), nullable=False),
    sa.Column('request_schema', sa.JSON(), nullable=False),
    sa.Column('response_schema', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['code_symbols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_endpoints_file_id'), 'api_endpoints', ['file_id'], unique=False)
    op.create_index(op.f('ix_api_endpoints_http_method'), 'api_endpoints', ['http_method'], unique=False)
    op.create_index(op.f('ix_api_endpoints_route_path'), 'api_endpoints', ['route_path'], unique=False)
    op.create_index(op.f('ix_api_endpoints_service_id'), 'api_endpoints', ['service_id'], unique=False)
    op.create_index(op.f('ix_api_endpoints_symbol_id'), 'api_endpoints', ['symbol_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_analysis_run_id'), 'evidence', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_type'), 'evidence', ['source_type'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('change_id', sa.String(length=36), nullable=True),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('factor_breakdown', sa.JSON(), nullable=False),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_analysis_run_id'), 'risk_assessments', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_change_id'), 'risk_assessments', ['change_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_project_id'), 'risk_assessments', ['project_id'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('symbol_id', sa.String(length=36), nullable=True),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('target_component', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['code_symbols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_file_id'), 'tests', ['file_id'], unique=False)
    op.create_index(op.f('ix_tests_project_id'), 'tests', ['project_id'], unique=False)
    op.create_index(op.f('ix_tests_repository_id'), 'tests', ['repository_id'], unique=False)
    op.create_index(op.f('ix_tests_symbol_id'), 'tests', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_tests_test_name'), 'tests', ['test_name'], unique=False)
    op.create_table('test_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('commit_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_executions_commit_id'), 'test_executions', ['commit_id'], unique=False)
    op.create_index(op.f('ix_test_executions_test_id'), 'test_executions', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_executions_test_id'), table_name='test_executions')
    op.drop_index(op.f('ix_test_executions_commit_id'), table_name='test_executions')
    op.drop_table('test_executions')
    op.drop_index(op.f('ix_tests_test_name'), table_name='tests')
    op.drop_index(op.f('ix_tests_symbol_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_repository_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_project_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_file_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_risk_assessments_project_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_change_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_analysis_run_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_evidence_source_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_analysis_run_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_api_endpoints_symbol_id'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_service_id'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_route_path'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_http_method'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_file_id'), table_name='api_endpoints')
    op.drop_table('api_endpoints')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_analysis_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_code_symbols_symbol_type'), table_name='code_symbols')
    op.drop_index(op.f('ix_code_symbols_name'), table_name='code_symbols')
    op.drop_index(op.f('ix_code_symbols_file_id'), table_name='code_symbols')
    op.drop_table('code_symbols')
    op.drop_index(op.f('ix_analysis_runs_project_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_change_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_files_snapshot_id'), table_name='files')
    op.drop_index(op.f('ix_files_repository_id'), table_name='files')
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.drop_index(op.f('ix_files_language'), table_name='files')
    op.drop_index(op.f('ix_files_is_test'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_changes_repository_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_project_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_commit_id'), table_name='changes')
    op.drop_table('changes')
    op.drop_index(op.f('ix_scenario_results_scenario_id'), table_name='scenario_results')
    op.drop_table('scenario_results')
    op.drop_index(op.f('ix_runtime_events_service_id'), table_name='runtime_events')
    op.drop_index(op.f('ix_runtime_events_project_id'), table_name='runtime_events')
    op.drop_index(op.f('ix_runtime_events_event_type'), table_name='runtime_events')
    op.drop_table('runtime_events')
    op.drop_index(op.f('ix_repository_snapshots_repository_id'), table_name='repository_snapshots')
    op.drop_index(op.f('ix_repository_snapshots_commit_hash'), table_name='repository_snapshots')
    op.drop_table('repository_snapshots')
    op.drop_index(op.f('ix_database_entities_service_id'), table_name='database_entities')
    op.drop_index(op.f('ix_database_entities_project_id'), table_name='database_entities')
    op.drop_index(op.f('ix_database_entities_entity_name'), table_name='database_entities')
    op.drop_table('database_entities')
    op.drop_index(op.f('ix_configurations_service_id'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_project_id'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_config_key'), table_name='configurations')
    op.drop_table('configurations')
    op.drop_index(op.f('ix_commits_repository_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_commit_hash'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_branches_repository_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_services_project_id'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_scenarios_project_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_repositories_project_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_incidents_project_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_dependencies_target_type'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_target_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_source_type'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_source_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_relation_type'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_project_id'), table_name='dependencies')
    op.drop_index('idx_dep_target', table_name='dependencies')
    op.drop_index('idx_dep_source', table_name='dependencies')
    op.drop_index('idx_dep_relation', table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
